Vagrant.configure('2') do |config|
  #config.vm.box = 'centos/7'
  config.vm.box = 'generic/ubuntu1604'
  config.vm.provider :libvirt do |ans|
	ans.memory = "1024"
	ans.cpus = 1
  end
  config.vm.hostname = 'Ansible'
  config.vm.network :private_network, ip: '10.10.10.10'
  config.vm.provision 'ansible' do |ansible|
    ansible.playbook = 'users.yml'
  end
end
