- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  
  tasks:
    - name: Install Python
      raw: test -e /usr/bin/python || (apt -y update && apt  install -y python)
    - name: install nginx
      apt: 
        name: nginx
        state: latest
    - name: ensure local user has a matching account on the host
      user:
        state: present
        name: "{{ lookup('env', 'USER') }}"
        shell: /bin/bash
        groups: sudo
      register: user

    - name: ensure local user's public key is on the host
      authorized_key:
        user: "{{ lookup('env', 'USER') }}"
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    # this should only be used for development!
    - name: ensure sudo group can sudo without a password
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: "^%sudo"
        line: "%sudo\tALL=(ALL:ALL) NOPASSWD:ALL"
        validate: "visudo -cf %s"
